### ISSUE TITLE
Unable to connect: 7 couldn't connect to host

### ISSUE THREAD

**Issue by wuzesheng** [nategood/httpful#159]
Hi there,
I have a restful service, and also have Java and PHP SDKs. We run periodical testing programs with both of the SDKs separately. The Java SDK runs normally, but the PHP SDK, which is implemented via the Httpful library, reports exception "Httpful\Exception\ConnectionErrorException: Unable to connect: 7 couldn't connect to host'' occasionally. 

Anybody can help on this?

BTW: the httpful library version is 0.2.17

**Comment by nategood** [comment]
Would need a lot more information about the environment to learn more about what might be going on.
