### ISSUE TITLE
Uploading file with post data in the same request.

### ISSUE THREAD

**Issue by gabrielkaputa** [nategood/httpful#160]
Hi, is it possible to upload a file and send some post data in the same request? I'm can upload a file and send post data as well separately, but i cant get it work in the same request. can you give me an example if it is possible? thanks

**Comment by oretzl** [comment]
I'm experiencing the same issue - it crashes when I'm attaching first the file before the body.
If setting the body, the file is never transfered. This german was successful sending a file without post-body: https://www.tricd.de/php/php-file-uploads-mit-httpful/

Seems like curl_file_create() is broken in php 5.5.9
 
$request = \Httpful\Request::post("http://localhost/nodes");
$request->sendsType(Httpful\Mime::FORM);
$request->attach($files);
$request->body('{"name":"cspo"}');
$response = $request->send();

**Comment by gabrielkaputa** [comment]
It works for me if I upload the same files to a server. So I guess it is some settings or limitations on my localhost.
