### ISSUE TITLE
GET Request with JSON Payload

### ISSUE THREAD

**Issue by RacZo** [nategood/httpful#165]
Hey!

First of all, great job! Httpful is really very elegant and powerful.

Can httpful tperform a GET request with a JSON payload (JSON in the request body, not in the URL as a parameter)?

**Comment by RacZo** [comment]
Just to let you know that what I was asking for and wanted to do was possible, just had to tweak it a bit more. Thanks!

**Comment by MaxBaldin** [comment]
@RacZo you violating HTTP/1.1 spec in your application? It is very intresting case, please, provide more information about.

**Comment by nategood** [comment]
Thanks @RacZo. @maxbaldin was right, that breaks the rules of HTTP. If HTTP doesn't support it, HTTPful doesn't either :-(.
