### ISSUE TITLE
How to uncompress if response is gzip encoded.

### ISSUE THREAD

**Issue by msankhala** [nategood/httpful#171]
I was using some rest api to get the data and was using httpul to make the request but api send the response in gzip format which httpul was not able to decode. I think if httpful can detect the response encoding and use php gzdecode http://php.net/manual/en/function.gzdecode.php function to decode the response. Then we can get the response in text format.

**Comment by msankhala** [comment]
Following code works if your response is gzip:

```php
        $response = \Httpful::get($url)
        ->parseWith(function($body) {
                return gzdecode($body);
        })
        ->send();
```

**Comment by minhna** [comment]
It works. Thank you @msankhala.

**Comment by nategood** [comment]
:+1: Thanks @msankhala. Might add this as an example.

**Comment by msankhala** [comment]
@nategood `gzdecode` sometime throw the error if response is not valid gzip compressed and i didn't find any way to detect whether response is valid compressed or not. It would be great if HTTPful can detect this before trying to decode with `gzdecode` function.

**Comment by abmmhasan** [comment]
I know the question is too old but if anyone need a proper solution:

```
$response = \Httpful::get($url)
            ->parseWith(function($body) {
                if(0 === mb_strpos($body, "\x1f" . "\x8b" . "\x08", 0, "US-ASCII")){
                    return gzdecode($body);
                }
                return $body;
            })
            ->send();
```
