### ISSUE TITLE
PHPDoc comments need updating

### ISSUE THREAD

**Issue by Ugoku** [nategood/httpful#174]
For example, Request.php line 194 (send function) says `* @return string|associative array of parsed results`
This is [not supported by PHPDoc](https://github.com/phpDocumentor/phpDocumentor2/issues/1118) so should be updated to `* @return string|array associative array of parsed results` for example.
Request.php line 292 (hasClientSideCert) and 495 (hasProxy) do not indicate they return a boolean.

Should I submit a PR for this, or will you look into this yourself?

**Comment by martinlindhe** [comment]
resolved in #180

**Comment by Ugoku** [comment]
Awesome, let's hope this gets pulled into master.
