### ISSUE TITLE
Stripping of proxy headers fails

### ISSUE THREAD

**Issue by Cheezykins** [nategood/httpful#178]
Hi,

When adding in a proxy with httpful, the parsing of the proxy headers (well, stripping using regex) fails for some proxies.

Fiddler2 for example returns HTTP/1.1 200 Connection Established (note the capital E) rather than HTTP/1.1 200 Connection established, leading the regex to fail to match and the whole header parsing to fail.

This means that the response body contains all headers after the proxy headers, and things like XML parsing throw an exception.

I would recommend adding the i case insensitive flag to the regex [here](https://github.com/nategood/httpful/blob/master/src/Httpful/Request.php#L218)

```php
$proxy_regex = "/HTTP\/1\.[01] 200 Connection established.*?\r\n\r\n/si";
```

**Comment by Cheezykins** [comment]
Created a [pull request](https://github.com/nategood/httpful/pull/179)

**Comment by nategood** [comment]
Merged PR but failed to close this case out. Thanks.
