### ISSUE TITLE
on the post body , using http_build_query

### ISSUE THREAD

**Issue by BardiaAfshin** [nategood/httpful#185]
the payload variable on the post body, you have to utilize a method from php (http_build_query).

Why not have a flag that implicitly sets this up for the user?

something like this

```php
...
$request->post($uri, $my_payload_array);
```

instead of what you do right now

```php
...
$request->post(uri, http_build_query($my_payload_array));
```

thoughts?

**Comment by DanMan** [comment]
Why reinvent the wheel?

**Comment by nategood** [comment]
Agree with @DanMan, but open to a PR that nicely wraps `http_build_query` as long as its backwards compatible.
