### ISSUE TITLE
Doesn't work!

### ISSUE THREAD

**Issue by cja-github** [nategood/httpful#191]
From http://phphttpclient.com I followed "Install option 1" and the first "quick snippet".

I end up with the following, with Request undefined.

![image](https://cloud.githubusercontent.com/assets/5276879/8760933/78af8f82-2d2f-11e5-935f-914d6c6a4925.png)

![image](https://cloud.githubusercontent.com/assets/5276879/8761175/2b672c8e-2d3a-11e5-9c2f-ab8fded182f2.png)

Additionally, and perhaps relatedly, I am confused by the fact that one of the code samples says "$response = Request::get" and another says "$response = \Httpful\Request::get". Is the latter valid PHP?

I have PHP 5.6.7.
![image](https://cloud.githubusercontent.com/assets/5276879/8761227/e10ac6de-2d3c-11e5-8dce-c7ef0b43f2ee.png)

What am I doing wrong?

**Comment by tcdaly** [comment]
I had the same problem.  I think you're supposed to put **\Httpful** in front of every class name.  The code examples clearly need updating.

**Comment by cja-github** [comment]
Is it worth using, despite the code samples?

On 19 July 2015 at 20:48, Thomas <notifications@github.com> wrote:

> I had the same problem. I think you're supposed to put *\Httpful* in
> front of every class name. The code examples clearly need updating.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nategood/httpful/issues/191#issuecomment-122697870>.
>



-- 
Christopher Alexander
cja@cja.org.uk

**Comment by tcdaly** [comment]
It might be, if you're willing to play around to work out how it works.  For the application I have in mind I think there will be a time saving.  Alternative would be PHP cURL.

**Comment by nategood** [comment]
The examples that don't include the namespace work if you use `use`. This is pretty common practice. For example:

```php
<?php
use \Httpful\Request;
Request::get(...);
```
