### ISSUE TITLE
PHAR is outdated

### ISSUE THREAD

**Issue by DanMan** [nategood/httpful#197]
The one to download from either http://phphttpclient.com/httpful.phar or http://phphttpclient.com/downloads/httpful.phar is version 0.2.10, so from 2013. There are none inside the release ZIPs either.

Y U NO UPDATE?!? CAN I HAZ NU PLZ??

j/k

**Comment by matsprea** [comment]
You can easily create a phar, the `build` script is already there.

**Comment by DanMan** [comment]
It worked. Thanks.

**Comment by nategood** [comment]
DanMan is correct, but I have updated the phar on the main site. Thanks.
