### ISSUE TITLE
want to get the httpd code returned

### ISSUE THREAD

**Issue by BardiaAfshin** [nategood/httpful#198]
I want to get the http code returned from Request method, in the Response object, I don't see an apparent way to get the http response code

**Comment by DanMan** [comment]
IIRC the returned object has a `code` property which holds the HTTP status code.

**Comment by BardiaAfshin** [comment]
```php
$response = $request->send()..
echo "$response->code is the HTTP status code"
```

will allow displaying the code?

**Comment by nategood** [comment]
Yes. That is correct.
