### ISSUE TITLE
Test needs to be updated

### ISSUE THREAD

**Issue by abantecart** [nategood/httpful#279]
tests/Httpful/requestTest.php and tests/Httpful/HttpfulTest.php needs to be updated. 

PHPUnit 6 or 7 no longer have PHPUnit_Framework_TestCase,

Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /home/travis/build/nategood/httpful/tests/Httpful/HttpfulTest.php on line 24

**Comment by nategood** [comment]
Resolved in 0.3.0
