### ISSUE TITLE
Your website's domain has expired

### ISSUE THREAD

**Issue by crismanNoble** [nategood/httpful#280]
Your readme makes multiple references to http://phphttpclient.com/, but when I go to it I get a notice that 
```This domain is expired. If you're the owner, you can renew it. If you're not the owner, search for your next domain and then build your website for free on Dynadot.com!```

I am unable to find docs anywhere else, this is my favorite http lib, please don't let it disappear. Maybe the docs should migrate to github?

**Comment by arjanvlek** [comment]
Experienced the same. Let's hope it gets renewed by the owner. In the meantime, you can visit [http://web.archive.org/web/20181228044149/http://phphttpclient.com/](http://web.archive.org/web/20181228044149/http://phphttpclient.com/) to view the documentation

**Comment by dreamon11** [comment]
Hi all,
Does anyone has a copy of httpful.phar file please? 

Thanks!

**Comment by nategood** [comment]
Welp. Someone picked it up and has it set to the original HTML. Wasn't me though.
