### ISSUE TITLE
Issue with httpful.phar include

### ISSUE THREAD

**Issue by rkshakya** [nategood/httpful#62]
I am using the latest version(httpful-0.2.0.phar) of HTTPFul phar. On the hosted setup I get following problem:
I have included phar as 
include "./httpful.phar";
..........................
PHP Warning:  include(): Failed opening 'phar://httpful.phar/Httpful/Bootstrap.php' for inclusion (include_path='.:') in /var/www/tut/soapsync/httpful.phar on line 4
PHP Fatal error:  Class 'Httpful\Bootstrap' not found in /var/www/tut/soapsync/httpful.phar on line 5

while on my local(dev) setup it works fine.

**Comment by llamafilm** [comment]
I think this issue should be reopened.  I get the same problem running PHP 5.3.1.  I downloaded the latest version and use include('httpful.phar').  When I open the phar file it says `VERSION = '0.2.19'`.
This php code:
```
include('httpful.phar');
$response = \Httpful\Request::get('http://example.com')->send();
```
Produces this error:
```
??????.?
Fatal error: Class 'Httpful\Request' not found in /Applications/XAMPP/xamppfiles/htdocs/owncloud/action.php on line 3
```

I'm no php expert, but I do notice this at the top of the phar file, is this a problem with all the weird characters?
```
__HALT_COMPILER(); ?>
àhttpful.pharHttpful/Bootstrap.phpÆ	≥π˝UÆ	ó⁄˝w∂.Httpful/Exception/ConnectionErrorException.php\≥π˝U\≈"Ç∂Httpful/Handlers/CsvHandler.phpÄ≥π˝UÄΩ”Út∂ Httpful/Handlers/FormHandler.php&≥π˝U&˛Â∂ Httpful/Handlers/JsonHandler.phpÕ≥π˝UÕl2•¿∂'Httpful/Handlers/MimeHandlerAdapter.php»≥π˝U»∞#À∂Httpful/Handlers/README.mdØ≥π˝UØ˜ut∂!Httpful/Handlers/XHtmlHandler.php?≥π˝U?Å≈∂Httpful/Handlers/XmlHandler.phpW≥π˝UWë◊è∂Httpful/Http.php≥π˝UGvÅ∂Httpful/Httpful.phpÉ≥π˝UÉXÎ°∂Httpful/Mime.phpÆ≥π˝UÆdﬂî∂Httpful/Request.php˛è≥π˝U˛èsFY∂Httpful/Response/Headers.phpÈ≥π˝UÈr∑ı∂Httpful/Response.php¯≥π˝U¯Nsü˘∂Httpful/Proxy.php≥π˝UNƒæ2∂<?php
```
