### ISSUE TITLE
Fatal error: Class 'Request' not found

### ISSUE THREAD

**Issue by alexlangberg** [nategood/httpful#90]
Hello

Maybe I'm just new at this but I get this error no matter if I use the .phar or install using Composer (successfully). Monolog works so I don't think it's a problem with Composer. I've tried downgrading but to no avail, still the same error:

Fatal error: Class 'Request' not found in <path>

I've tried both the Twitter and Google samples but it seems to be some kind of include problem?

**Comment by FlominatorTM** [comment]
What about including that line in the examples on the website?

**Comment by ffmit** [comment]
Same issue here, I also recommend the idea of FlominatorTM.

**Comment by nategood** [comment]
All of the examples on the homepage do show either using the "use" syntax or use the full namespace. Let me know if I'm missing something.

**Comment by FlominatorTM** [comment]
No clue if you fixed it meanwhile or if @ffmit  , @alexlangberg  and me were blind, but am not able to reproduce the problem.
